# CAMBIO CLAVE: Usamos Node 22 en lugar de 18
FROM node:22-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# ETAPA 2: Servidor Web (Nginx)
FROM nginx:alpine
COPY --from=build /app/dist/retrogames /usr/share/nginx/html
EXPOSE 80
