# ETAPA 1: Construcción (Node 22)
FROM node:22-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# ETAPA 2: Servidor Web (Nginx)
FROM nginx:alpine

# --- EL CAMBIO CLAVE ESTÁ AQUÍ ---
# Añadimos '/browser' al final de la ruta de origen
COPY --from=build /app/dist/retrogames/browser /usr/share/nginx/html
# ---------------------------------

EXPOSE 80
