# ETAPA 1: Construcción
FROM node:22-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# ETAPA 2: Servidor Web (Nginx)
FROM nginx:alpine

# Borramos la config por defecto de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copiamos NUESTRA configuración (el archivo que acabas de subir)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiamos la web compilada
COPY --from=build /app/dist/retrogames/browser /usr/share/nginx/html

EXPOSE 80
